### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by ImBadImSorry** [JaraLowell/OgarServ#132]
This is the error I get when doing jx index.js

jx is already in the directory.

`module.js:776`
throw err;
      ^
Error: Cannot find module 'underscore'
    at Function.Module._oldRes (module.js:774:9)
    at Function.Module._resolveFilename (module.js:1606:15)
    at Function.Module._load (module.js:335:17)
    at Module.require (module.js:451:15)
    at require (module.js:469:13)
    at Object.<anonymous> (C:\Users\KDWhite\Documents\GitHub\OgarServ\src\GameSe
rver.js:4:9)
    at Module._compile (module.js:595:24)
    at Object.Module._extensions..js (module.js:625:8)
    at Module.load (module.js:416:30)
    at Function.Module._load (module.js:380:8)``

**Comment by JaraLowell** [comment]
jx install ws http fs sys mysql url underscore
