### ISSUE TITLE
Server crashes when being joined?

### ISSUE THREAD

**Issue by ChefHunter** [JaraLowell/OgarServ#144]
????????

---

  / _ \ __ _ __ _ _ _  / **| ___ _ ___ ___** _ _
 | (_) / _`/ _` | '_| __ \/ -_) '_\ V / -_) '_|
  _**/\**, __,_|_|   |___/_**|_|  \_/_**|_|
       |___/  An open source Agar.io server

 Node.js v5.0.0 (win32 x64)
 Chrome's V8 JavaScript engine v4.6.85.28
 Library HTTP v2.5.0
 Library zlib v1.2.8

[21:30] \* Loading AI Bot System...
[21:30] \* Listening on port 4411
[21:30] \* Current game mode is Free For All
[21:30] \* Auto shutdown after 48 hours
[21:30] \* Protocol set to new, clients with version 561.20 and up can connect to
 this server
[21:30](Play:0 Spec: 0) Client connect: 127.0.0.1:52193 (1) [origin http://agar
.io/]
C:\Users\Hunter\Desktop\OgarServ-master\OgarServ-master\src\PacketHandler.js:42
                var charCode = view.getUint16(i, true);
                                    ^

RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint16 (native)
    at PacketHandler.handleMessage (C:\Users\Hunter\Desktop\OgarServ-master\Ogar
Serv-master\src\PacketHandler.js:42:37)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onbinary (C:\Users\Hunter\Desktop\OgarServ-master\OgarServ-maste
r\node_modules\ws\lib\WebSocket.js:848:10)
    at C:\Users\Hunter\Desktop\OgarServ-master\OgarServ-master\node_modules\ws\l
ib\Receiver.js:628:18
    at Receiver.applyExtensions (C:\Users\Hunter\Desktop\OgarServ-master\OgarSer
v-master\node_modules\ws\lib\Receiver.js:371:5)
    at C:\Users\Hunter\Desktop\OgarServ-master\OgarServ-master\node_modules\ws\l
ib\Receiver.js:604:14
    at Receiver.flush (C:\Users\Hunter\Desktop\OgarServ-master\OgarServ-master\n
ode_modules\ws\lib\Receiver.js:347:3)
    at Receiver.opcodes.2.finish (C:\Users\Hunter\Desktop\OgarServ-master\OgarSe
rv-master\node_modules\ws\lib\Receiver.js:633:12)
 Press any key to continue . . .

**Comment by EnTerr** [comment]
Ooh, that's not good! Regardless the client, server should not crash, hmm. 

Is somebody trying to use MiniClit's client^ against OgarServ? I'll take a random guess that in protocol 6/7 they have changed the nickname string from UTF-16 to UTF-8. So an empty nickname will come as one byte \0 instead of \0 \0

I propose when receiving connection from a client, OgarServ pay attention to the protocol declared in packet 254 and if >5, assume UTF8 strings.

(^) actually it is! saw above "origin http://agar.io/"

**Comment by ChefHunter** [comment]
Yeah. I was testing with agar.io. what can I do to fix?

**Comment by Andrews54757** [comment]
moneyclip is stupid. Dont support them. All they want is money

**Comment by JaraLowell** [comment]
Not really sure what they mean in there post http://blog.miniclip.com/2016/05/20/private-servers-back-agar-io/ like what small changes to allow it, with zero hint on what this means for the community. So first we give our players a kick in the ass and then a half eaten candy bit to make good? Any ways, will probably need to check  for all packages what the new clients want and sends. If it be send in `view.getUint8` and if it wants it back in int8. This has noting to do with UTF as that always bin UTF8 just 2 bytes for 16, 4 for 32.... just mixing them together. Server did not do that, your client did. :P

**Comment by EnTerr** [comment]
@JaraLowell - you don't have to bother supporting protocol > 5.

However: OgarServ should not die like this when contacted by the current Agar.io web client. It means that any "innocent" person trying to use that against known IP will be killing the server and booting everyone else from there. The simplest fix you can do is check 0xFE package and if version is >5, kick those clients :-) since they are "dangerous" to server's health.

**Comment by JaraLowell** [comment]
Actually i just also "killed" the Agar.io web client.. as a test...
so yes nickname is sent by agar.io as int8 but because OgarServ sends every thing back NOT as int8, you kill the client on connect. 

> ```
>     case 0:
>         // Set Nickname
>         var nick = '';
>         for (var i = 1, llen = view.byteLength; i < llen; i++) {
>             var charCode = view.getUint8(i, true);
>             if (charCode == 0) {
>                 break;
>             }
>             nick += String.fromCharCode(charCode);
>         }
>         this.setNickname(nick);
>         break;
> ```

This works however, you kill the client because we do not speak the same language back. New protocol basically wants everything send at int8 So basically, if we now make OgarServ compatible with agar.io then no other client will work after including my own client. As there no way to know in advance what type of client is connecting.

**Comment by EnTerr** [comment]
@JaraLowell - not true re "no other client will work after including my own client". Please read above what i said in 
https://github.com/JaraLowell/OgarServ/issues/144#issuecomment-220754177 !

The idea being to check what protocol is requested in 0xFE. That will determine a per-session (per-client) setting:
- if protocol requested there is 5 or lower - use UTF16 (2 bytes per character in strings, end with \0 \0. Or getUint16/setUint16() in your vernacular)
- if protocol requested is 6 or higher - use UTF8 (1 byte per character in strings, end with a single \0 byte; i imagine `getUint8/setUint8()` for you; **only for strings**)

You don't need to re-work your server now (or ever) to support Agar.io client - but you can put a simple check `if packet_no_254.version > 5 then kick_client()` for now (or forever).

DEFINITELY do not change your server to handle only MiniClit's new protocol though and leave the other clients in the cold.

**Comment by JaraLowell** [comment]
To be fair, i do not think that i with OgarServ want to support the new protocol (int8 all) as it be just a shit to have multiple protocols like that in one server. Mean not impossible, but just ble annoying when you want to do changes later on the road. But above all, having to work trough multiple ways of how to send a client something, is not an improvement for the server but rather, an cause of lag.

**Comment by EnTerr** [comment]
So don't support it - i won't blame you :)
Just check client version in 0xFE and politely decline if >5.

**Comment by Barbosik** [comment]
Look at this fix, may be you can reuse something: https://github.com/OgarProject/Ogar/issues/588

It supports both protocols 5 and 7 with automatic switch (include utf-8/unicode).

Also, note that since protocol 5, there is a new Clear Message 0x12 instead of 0x14 (which was used in protocol 4). The new client uses 0x12. I added this info here: https://github.com/issy123/agario-protocol/issues/15
This message is important and should be send at begin of a new connection and before any join command.

**Comment by EnTerr** [comment]
There is no incentive for indie servers to support Agar.io client - if they do, that just means MiniClit will monetize by showing ads in browser while using other's private server. Arguably, there is now incentive for private server owners **not** to accept Agar.io origin.

And there is no "tit-for-tat" - since lately MC have taken active steps to prevent 3rd party clients from connecting to Agar.io "official" servers.

**Comment by Barbosik** [comment]
May be you're right, I hope that it will not leads to disappearing of private servers at all

**Comment by JaraLowell** [comment]
Think eventually one needs decide, Create and maintain a server for private or for agar.io; As mixing the protocols in to one server, even though possible; will lead to more memory use and overall server performance. Or more per say lag. Simplicity is, if i change OgarServ to be compatible again with agar.io I render my own client useless. And render all private clients useless. While i think for Project Ogar they should stay up to par with agar.io, but i think OgarServ will stay as is for now protocol 4 and 5 only and not 6 (current agar.io) even though i am looking in to the case of adding the option to switch maybe. Will need see if there is a need for it by the community.

**Comment by Barbosik** [comment]
It's your decision, but I recommend to stay at protocol 6, because it has much better performance and server can handle much more players at the same performance with protocol 6

**Comment by EnTerr** [comment]
@Barbosik - what do you mean "stay at protocol 6", that's the one that introduced the P.I.T.A. compression, right? If so, how is that "stay", sound more like "invest time to implement compression",  with a doubtful payoff?

What do you mean by "much better performance and server can handle much more players at the same performance" - give link to data?

**Comment by JaraLowell** [comment]
i would wonder about the 'can handle more' as well, as in end, it the client that cant handle enough specially when it a handheld. Server wise, it wont truly matter as in end the only thing changed is the packages send so in that you see no speed boost or speed loss if running dedicated 6 or dedicated 5.

**Comment by Barbosik** [comment]
@EnTerr: no, I didn't mean compression packet. I'm talking just about difference in cell update packet. 

Protocol 6 needs to serialize less data, it can skip color data for example. For example when server needs to send cell update for 1000 ejected mass, it needs to send 5000 bytes more with protocol 5. It includes time to serialize these additional bytes, to allocate more memory in the websocket. There is need more time to send the packet. etc

**Comment by Barbosik** [comment]
@JaraLowell:  _Server wise, it wont truly matter as in end the only thing changed is the packages send so in that you see no speed boost or speed loss if running dedicated 6 or dedicated 5_

You're wrong. Protocol 6 allows to skip a lot of data which is already sent to the client in the previous packets. It allows to reduce packet length significantly. As result, packets is more small, they has less duplicated data. Server spend less time on data serialization. WebSocket allocates less memory to send it. There is need less time to send it because packet is more small. Server uses less network traffic.

I tested it on MultiOgar which supports both protocols and I can say that difference is very noticeable, if you have a lot of cells on the screen. When you connected through protocol 6 it has less lags, even if you connected to localhost. Protocol 6 can handle more cells than protocol 5.

On real network the difference even much more noticeable. 

The packet length is real bottle neck in ogar servers and protocol 6 allows to reduce impact of this bottle neck significantly.

**Comment by EnTerr** [comment]
@Barbosik - so still have to re-implement differences from 5 to 6. Are these even described clearly somewhere (outside of your source)? There is nothing in http://agar.gcommer.com/Protocol (i personally already forgot what we were discovering a few months ago wiresharking)

Also, do you have real benchmarks on comparing v5 to v6 fairly - or is it "anecdotal" as they say?

**Comment by Barbosik** [comment]
Actually, the packet length is the reason why moneyclip added new packet in the protocol 6 which allows to send any other packet in compressed form. WebSocket per message deflate works very slow and eats a lot of cpu, I tested it on my servers and it add very significant lags.
They used extremely fast realtime LZ4 compression which allows to spend less cpu time on data compression. So, they can send much smaller packets and with low cpu load. It reduce lags very significantly. Especially if you have a lot of players on the server. 

Compression packet allows to eliminate cell name duplication. It very important when your cell exploded on the virus. In such case server needs to send up to 15 new cells, and all of them has the same name...

Also, protocol 6 uses UTF-8 which is 2 times smaller thant Unicode. It also improve performance and reduce trafic very significantly.

**Comment by EnTerr** [comment]
You contradict yourself - earlier you said "no, I didn't mean compression packet. I'm talking just about difference in cell update packet." for that same protocol 6. I guess now you are saying it's the compression that's important? I remain skeptical based on what i saw month ago, LZ4 was weak - also usage is a trade-off between increasing CPU load and decreasing network bandwidth.

But again - benchmarks comparing apples to apples?

**Comment by Barbosik** [comment]
@EnTerr: no, there is no contradict. 

For example when your cell is exploded on the virus, we can compare difference in packet length to send 15 strings with name:

| Protocol | Strings data length which needs to send |
| --- | --- |
| 5 | 16 \* 2 \* 15 = 480 [bytes] |
| 6 (without using compressed packed) | 16 \* 15 = 240 [bytes] |
| 6 (with using compressed packet) | 16 + 3*15 = 61 [bytes] |

it's just difference on strings. But there is also difference with using flags for optional fields.

As you can see, protocol 6 even with no compression has much better performance. 
But if you will use LZ4 compression, it gets just fantastic results

**Comment by Barbosik** [comment]
@EnTerr: _I remain skeptical based on what i saw month ago, LZ4 was weak_

There is no need for best compression. There is need for any kind of compression but maximum fast and with minimum cpu usage. It should be fast as much as possible. And LZ4 is the best choice for that, because it very fast and agario packets is very easy to compress with using LZ4 with no complicated logic. It especially designed for realtime compression.

The difference with other compression type is not significant, +- a hundred of bytes on 30-60k message is just nothing. But performance is very and very important. This is why LZ4 is used.

**Comment by JaraLowell** [comment]
thats bandwith, somting that was never an issue for any of the servers; it the math of movement and the likes thats the killer; so again; all that changed is the package in 5 vs 6 the internal is the same engine needing the same cpu power.

**Comment by Barbosik** [comment]
@JaraLowell: thats bandwith, somting that was never an issue for any of the servers

protocol efficiency is very and very important, especially for server for realtime game, such as agario. You should count each byte in the packet, because it affects server performance. It's not about theoretical network bandwidth. It's about CPU load. memory allocations, etc.

For example, when I used not optimized protocol with large messages (the same as ogar), I noticed delays in server update interval with peaks up to 100-200 milliseconds on the server with just 10 players. After optimization which goal is just to reduce packet length, I get stable 40 ms update with no peaks even with 20 players. The server has 1 Gigabit internet bandwidth, but it doesn't helps when you use large packets.

Protocol 6 allows to send smaller packets, smaller at least for 5 bytes on each cell even with no using compressed message. It means that you need to spend less CPU time on packet serialization - it affects server CPU load. It means that you need to allocate less memory. I found that node.js has some threshold in performance if you allocate large amount of memory (it's triggered on packet with 11000+ cells even with my protocol optimizations). It means that websocket needs less CPU time to encode message into websocket protocol - smaller server CPU load. It means that websocket needs less memory allocations - again smaller server CPU load. It means that server needs to send smaller packets through network layer, it means that it needs less memory allocations to enqueue all these bytes - again smaller server CPU load.

**Comment by JaraLowell** [comment]
In end, you did a good job on multi ogar :smile: though i would probably have done a few things differently. However as your change is so big and unique i would not take it without for example your approval and even if i do,. would be a while before i have what i want in the way i want it; As you did one thing all others did to the one thing that caused most server side lag. Something i need thing about in an integration, nor do i want to load the whole reader and writer per user as that just memory use that is unneeded, i bin looking in to it to get it in trough game server like we also pull in the ini.js but allas it just re thinking a few things without killing the whole objective :smiling_imp:
