### ISSUE TITLE
Cant play..

### ISSUE THREAD

**Issue by raphyjb** [JaraLowell/OgarServ#148]
when i try to play,it shows my bubble.. and i cant move can do anything else..really wierd
Error: listen EADDRINUSE :::88
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at StatServer.start (C:\Users\Maurice\Desktop\Ogar-unlimited-master\src\core\StatServer.js:29:21)
    at GameServer.start (C:\Users\Maurice\Desktop\Ogar-unlimited-master\src\core\GameServer.js:487:21)
    at ControlServer.start (C:\Users\Maurice\Desktop\Ogar-unlimited-master\src\core\ControlServer.js:60:21)
    at Multiverse.create (C:\Users\Maurice\Desktop\Ogar-unlimited-master\src\core\Multiverse.js:22:7)
    at Multiverse.init (C:\Users\Maurice\Desktop\Ogar-unlimited-master\src\core\Multiverse.js:42:26)
TypeError: this.log is not a function
    at GameServer.err (C:\Users\Maurice\Desktop\Ogar-unlimited-master\src\core\GameServer.js:300:16)
    at emitOne (events.js:90:13)
    at WebSocketServer.emit (events.js:182:7)
    at Server.WebSocketServer._onServerError (C:\Users\Maurice\Desktop\Ogar-unlimited-master\node_modules\ws\lib\WebSocketServer.js:82:50)
    at emitOne (events.js:90:13)
    at Server.emit (events.js:182:7)
    at emitErrorNT (net.js:1253:8)
    at _combinedTickCallback (node.js:383:13)
    at Immediate._tickCallback [as _onImmediate](node.js:407:11)
    at tryOnImmediate (timers.js:534:15)

> [Console] We recieved a world-wide message!: Hello, Please take this survey (http://goo.gl/forms/oZKMBudTnVvgD3n62) as we decide on the future of ogar unlimited.
> [OK] Uniban updated

**Comment by ItzLevvie** [comment]
Please report your issue over here: https://github.com/AJS-development/Ogar-unlimited/issues
