### ISSUE TITLE
 Cannot read property 'destroy' of null

### ISSUE THREAD

**Issue by SomeoneCares11** [JaraLowell/OgarServ#171]
The server crashes and that what i get 

[FATAL] TypeError: Cannot read property 'destroy' of null
    at WebSocket.onClose (/home/agar/src/GameServer.js:288:23)
    at emitTwo (events.js:111:20)
    at WebSocket.emit (events.js:191:7)
    at WebSocket.emitClose (/home/agar/node_modules/ws/lib/WebSocket.js:224:10)
    at _receiver.cleanup (/home/agar/node_modules/ws/lib/WebSocket.js:210:41)
    at Receiver.cleanup (/home/agar/node_modules/ws/lib/Receiver.js:500:15)
    at WebSocket.finalize (/home/agar/node_modules/ws/lib/WebSocket.js:210:22)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)

**Comment by ItzLevvie** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/issues/492#issuecomment-277460015

**Comment by SomeoneCares11** [comment]
Thank you.
