### ISSUE TITLE
Start Problems

### ISSUE THREAD

**Issue by CAvciii** [JaraLowell/OgarServ#172]
Hello,

I am writing the **sh runnode.sh** command to start the console. But I get an error like below.

```
/root/life/node_modules/ws/index.js:9
const WebSocket = require('./lib/WebSocket');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/life/GameServer.js:2:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by ItzLevvie** [comment]
Do ```node --version``` in the terminal.

Make sure you're on 6.0.0+ or 7.0.0+
