### ISSUE TITLE
erorr Stopped game

### ISSUE THREAD

**Issue by malekksa505** [JaraLowell/OgarServ#180]
Hello ,,

i have problem to Ogarserv for vps

test erorr :
`
[00:39:21] TypeError: Cannot read property 'writeScore' of undefined
    at PlayerTracker.resetstats (/root/OgarServ/src/PlayerTracker.js:243:34)
    at GameServer.resolveCollision (/root/OgarServ/src/GameServer.js:1395:27)
    at GameServer.updateMoveEngine (/root/OgarServ/src/GameServer.js:1058:14)
    at GameServer.mainLoop (/root/OgarServ/src/GameServer.js:791:14)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
[00:39:21] process.exit(1)
`

**Comment by malekksa505** [comment]
@MastaCoder @JaraLowell

**Comment by malekksa505** [comment]
!!!!

**Comment by TheFlyingVoid** [comment]
Same problem here. Seems to happen when two big players eat each other.

**Comment by TheFlyingVoid** [comment]
I think it has something to do with dumping the data into SQL and it not being able to dump so the server throws and error.

**Comment by JaraLowell** [comment]
i do not even seem to check there if MySQL is active or not; witch truly is a boo boo from my end presuming it always on LOL *mutters* Let me look in to this one, as it should not call it when gameserver.mysql is not loaded.

**Comment by TheFlyingVoid** [comment]
Thank you. That fixed it!
