### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Niall7459** [JaraLowell/OgarServ#188]
My server was lagging a bit today, like alot freezing every 10 seconds or so.
Usually doesnt happen.

And then this afternoon the server appeared to be crashed

I resatrted and I lost the log file..

**Comment by Niall7459** [comment]
I remember it saying


'writable'

**Comment by Niall7459** [comment]
Here is log @JaraLowell 

TypeError: Cannot read property 'writable' of null
    at PlayerTracker.sendUpdate (/home/pi/Desktop/OgarServ Halloween/src/PlayerTracker.js:380:29)
    at GameServer.updateClients (/home/pi/Desktop/OgarServ Halloween/src/GameServer.js:912:39)
    at GameServer.mainLoop (/home/pi/Desktop/OgarServ Halloween/src/GameServer.js:804:10)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
[18:33:28] process.exit(1)
