### ISSUE TITLE
why does this error happen?

### ISSUE THREAD

**Issue by ghost** [JaraLowell/OgarServ#51]
**this happens when attempting to change gamemodes to hungergames (gamemode 11) :**
TypeError: Cannot read property 'length' of undefined
    at Mode.HungerGames.getPos (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\Ogar-devs\OgarServ-master\src - Copy\gamemodes\HungerGames.js:31:34)
    at Mode.HungerGames.onPlayerSpawn (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\Ogar-devs\OgarServ-master\src - Copy\gamemodes\HungerGames.js:160:44)
    at PacketHandler.setNickname (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\Ogar-devs\OgarServ-master\src - Copy\PacketHandler.js:224:34)
    at PacketHandler.handleMessage (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\Ogar-devs\OgarServ-master\src - Copy\PacketHandler.js:50:18)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onbinary (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\Ogar-devs\OgarServ-master\node_modules\ws\lib\WebSocket.js:823:10)
    at C:\Users\owner\Desktop\Agar.io Stuff\Private servers\Ogar-devs\OgarServ-master\node_modules\ws\lib\Receiver.js:537:18
    at Receiver.applyExtensions (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\Ogar-devs\OgarServ-master\node_modules\ws\lib\Receiver.js:364:5)
    at C:\Users\owner\Desktop\Agar.io Stuff\Private servers\Ogar-devs\OgarServ-master\node_modules\ws\lib\Receiver.js:531:14

**Comment by ghost** [comment]
**setting the gamemode to 11 in gameserver.ini gives this error:**
TypeError: Cannot read property 'config' of undefined
    at Cell.Food (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\Ogar-devs\OgarServ-master\src - Copy\entity\Food.js:10:24)
    at Mode.HungerGames.spawnFood (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\Ogar-devs\OgarServ-master\src - Copy\gamemodes\HungerGames.js:41:13)
    at Mode.HungerGames.onServerInit (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\Ogar-devs\OgarServ-master\src - Copy\gamemodes\HungerGames.js:118:10)
    at GameServer.start (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\Ogar-devs\OgarServ-master\src - Copy\GameServer.js:160:19)
    at Object.<anonymous> (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\Ogar-devs\OgarServ-master\src - Copy\index.js:30:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)

**Comment by ghost** [comment]
i tried the gamemode's code from the original ogar and got this: 
Skipping draw
agar.io.js?v=30:184 socket close

**Comment by ghost** [comment]
i believe its because i modified the splitting =\

**Comment by ghost** [comment]
nvm this
