### ISSUE TITLE
Coordinate scrambler for OgarServ

### ISSUE THREAD

**Issue by skyleter** [JaraLowell/OgarServ#76]
Please implement anti raga and coordinate scramber plus autoban to ogarserv :(
i copied the code of anti raga from Ogar-unlimited (thanks!) and worked but coordinate scrambler and autoban is giving me errors, cant add. Add this pls jara in the next release <_<

**Comment by skyleter** [comment]
p.s anti raga gives error too now :cry: ReferenceError: ipcounts is not defined
    at Object.close (/home/OgarServ/src/GameServer.js:249:13)
    at WebSocket.emit (events.js:98:20)
    at WebSocket.sendPacket (/home/OgarServ/src/GameServer.js:1201:14)
    at PlayerTracker.update (/home/OgarServ/src/PlayerTracker.js:168:21)
    at GameServer.updateClients (/home/OgarServ/src/GameServer.js:540:39)
    at GameServer.mainLoop (/home/OgarServ/src/GameServer.js:456:14)
    at wrapper [as _onTimeout](timers.js:277:14)
    at Timer.listOnTimeout [as ontimeout](timers.js:120:15)

**Comment by Andrews54757** [comment]
lol, my anti-copy/piratefrommycode tactic is working.

**Comment by Andrews54757** [comment]
(I made my code purposely messy and variables weird)

**Comment by JaraLowell** [comment]
### anti raga

No idea as of yet what this should be dooing...

### coordinate scrambler

is a bit pointless and adds only to a lot more calculations that be un needed over the effect you get. Beside right now; i would worry more about why it be most players log in twice or more then about bots. I would guess is shitty scripted stuff they have to make to login to rather then to listen in on the stream that is already active. But it will cause right now double the bandwidth for one player, and that is more an issue then a bot

### autoban

Auto ban what, mean to much chatting, to many hours played... wee bit more specific might be insightful. As if it be for ip's i wont add that. I have schools using my server and that means some time five to ten players from the same ip. So banning them will cost you players.

**Comment by Andrews54757** [comment]
He is trying to use my system, I have a good system that is unique because 1, It produces no lag (unlike other anti-ragas), 2 You can whitelist an IP so you can have exceptions, 3. You can edit all config feilds

**Comment by skyleter** [comment]
Thanks Andrew, im using OgarServ and Ogar-Unlimited at the same time. Both are very good so i dont plain to change this to this =P

anti raga [max connections per ip] => ban you or close socket, for example if this ip have more than 5 connections, socket close.

**Comment by Andrews54757** [comment]
But, since I like my anti-raga system a lot, I made it so that it is difficult to copy my code

**Comment by Andrews54757** [comment]
If you want it to be in ogarserv, you can ask and I will think about it

**Comment by Andrews54757** [comment]
(Even I cant make pull requests, I forgot all the wacky things I added)

**Comment by skyleter** [comment]
I like both. Sometimes i like to use ogarserv and sometimes ogar unlimited. Both are good acording to the things i want. Theres a ban file on ogar unlimited? [autosave]

**Comment by Andrews54757** [comment]
no, but I have added things over time so that people cant copy. Even iplimit wont work, try it, it still allows bots (if you copy)

**Comment by JaraLowell** [comment]
It be not that hard to do as we already count connections,. Though as stated, am not an fan off it. I would rather see a change in the community and communication server<->client as this whole duel login stuff to get a mini map working is just,. stupid. And un needed as you already have an active connection and thus can listen in with any other script. And people complain about lag.. wonder why.... lol

**Comment by Andrews54757** [comment]
Exactly, My anti raga system solves all your problems

**Comment by Andrews54757** [comment]
1. No Lag
2. Whitelisting

This is why I dont want people copying because i like it too much (like op)

**Comment by JaraLowell** [comment]
not it bans people i do not seek to get banned, nor do i go and have skype open 24/7 because people need be white listed,.. have a bit more to do then watch my server :P

**Comment by Andrews54757** [comment]
Yes but my system you enable autoban on or off, in my system, autoban and iplimits are seperate

**Comment by skyleter** [comment]
FIGHT FIGHT FIGHT!

**Comment by JaraLowell** [comment]
I think gone add a close on no activity. As those 'listeners'  send noting. And only 'spectate'  so if it not a real spectator. close conenction. Would prolly solve more then anything else :smile:

**Comment by Andrews54757** [comment]
I already did that

**Comment by skyleter** [comment]
Stop fighting, just asking jara to add coordinate scrambler, and ip limit[anti raga] and end at this :/

**Comment by Andrews54757** [comment]
We are not fighting

**Comment by Andrews54757** [comment]
@mogokcp Pls stop

**Comment by JaraLowell** [comment]
we sharing possibilities :stuck_out_tongue:

**Comment by Andrews54757** [comment]
yep

**Comment by Andrews54757** [comment]
We shpould just merge ogar unlimited with ogarserv

**Comment by Andrews54757** [comment]
(as they say, two heads are better than 1)

**Comment by skyleter** [comment]
ogarserv `+ ogar unlimited =======> rekt ogar

**Comment by skyleter** [comment]
:smile: yees should merge

**Comment by JaraLowell** [comment]
eheh, i truly do not mind having other people work with me, as we have several that commit. However, it has to always be a working server. Unlike some... projects out there that break due committers that well break something and then go sleep :smiling_imp:

**Comment by Andrews54757** [comment]
I dont do that. (If I do, its rare, smae with you)

**Comment by Andrews54757** [comment]
Lots of people are hovering between mine and yours, They would better like a new, rebranded,merged version that has features that would blow everyones minds

**Comment by JaraLowell** [comment]
never thought mine to be that special, mine is always live well... when i dont break it lol

**Comment by skyleter** [comment]
#WeWantOgarServUnLimited #SorrySpam

**Comment by Andrews54757** [comment]
actually, it searched up online and found many refrences to both our code

**Comment by Andrews54757** [comment]
1. at reddit
2. at google groups
3. ogarproject
4. ogar issues
5. other websites with other names

Also, other forks like Ogar plus are outdated

**Comment by JaraLowell** [comment]
@mogokcp it not ' we'  it you.

Ogar-Plus person is busy with school i believe, Ogar-Project, lately has committer issues. OgarServ well. is just my little side project where i keep adding things i find interesting for my server.

**Comment by Andrews54757** [comment]
(same here but i do a lot of adding)

**Comment by skyleter** [comment]
xd k. @Andrews54757 anti raga working fine. Thank you, tested.

**Comment by JaraLowell** [comment]
Told you @Andrews54757 add me to skype and we can play out some ideas :stuck_out_tongue_closed_eyes:

**Comment by Andrews54757** [comment]
oh please dont you see the rules at readme.md? DONT COPY MY ANTI RAGA SYSTEM!

**Comment by mogokcp** [comment]
I did? im using ogar unlimited and ogarserv at same time. Currently running ogar unlimited.

**Comment by mogokcp** [comment]
damn

**Comment by Andrews54757** [comment]
okay then it is okay

**Comment by Andrews54757** [comment]
( i was saying if you copy the code to anothers)

**Comment by Andrews54757** [comment]
(Im leaving this issue)

**Comment by skyleter** [comment]
So jara, do you will add anti bot (ip limit or cordinate scrambler) ? please...

**Comment by skyleter** [comment]
Rip. I think ill cant stop bots on my ogarserv server :cry:  but well, thanks ogar unlimited for this. That does not mean ill run it everytim. Jara and AJS should create a server [merge ogarserv+ogarUnlimited] | i think | .

**Comment by Andrews54757** [comment]
What is the difference? what does she have that I dont?

**Comment by skyleter** [comment]
Ill like if both merge, OgarServ does not have anti bots, and other things. So if merge you and Jara can have ideas and make the perfect server xD. I dont know if you will like this =P

**Comment by Andrews54757** [comment]
Whats the difference, Really, does ogarserv have anything that ogar unlimited doesnt?

**Comment by skyleter** [comment]
Ogarserv does not have anti raga :(

**Comment by skyleter** [comment]
ogar unlimited does not have option to [bot killed => not respawn] I THINK xD

**Comment by Andrews54757** [comment]
What do you mean? Do you mean that my server bots dont work or that your bots dont work.

**Comment by Andrews54757** [comment]
If you want your raga bots, you can disable the anti raga mech by whitelisting your ip or by editing the maxclientperip to like 500 (secound option not recommended if posting server)

**Comment by skyleter** [comment]
I mean, that Ogarserv does not have anti bot system /max ip :(, and no, i mean an option to disable this:

Bot die => no respawn, never back.
in ogar
bot die => respawn, back.

**Comment by Andrews54757** [comment]
You can disable, first turn off coordinate randomiser an then whitelist yourself

**Comment by Andrews54757** [comment]
Or if you want to disble for all players, change the maxclientperip value to 500

**Comment by skyleter** [comment]
what? 
Again

i said ogarserv does not have anti bot [thats sad! :( ill like anti bot on ogarserv]
1. I said, theres an option on ogar unlimited to prevent bots from respawning when they are killed?

**Comment by Andrews54757** [comment]
What bots are you talking about? Server bots?

**Comment by skyleter** [comment]
yes!

**Comment by Andrews54757** [comment]
Hmm

**Comment by Andrews54757** [comment]
Server bots shouldnt do that

**Comment by skyleter** [comment]
on ogarserv they do, when i do addbot to get mass i dont like too much because they respawn  :-(

**Comment by Andrews54757** [comment]
My bots should do the same thing...

**Comment by skyleter** [comment]
ah?

On ogarserv they dont respawn < i like that

**Comment by Andrews54757** [comment]
I fixed it, my bots now respawn (it was never a feature, it was a bug)

**Comment by skyleter** [comment]
what? ._:
oh nvm.....

**Comment by Andrews54757** [comment]
Oh you were talking about adding a feature where no bots respawn? I get it, i thought you meant there was a bug

**Comment by Andrews54757** [comment]
To make your bots dont respawn, 1, go in op mode, 2 press q untill 4 c's appear, 3, press space with mouse towards a bot. When he eats the virus, no bots can respawn

**Comment by skyleter** [comment]
Thank you. I will try.
