### ISSUE TITLE
Error Chat

### ISSUE THREAD

**Issue by morenja** [JaraLowell/OgarServ#82]
When i type somethign in chat my server stop i don't know why
/root/PacketHandler.js:197
                wstream.write('[' + gameServer.formatTime() + '] ' + wname + '
                                    ^
ReferenceError: gameServer is not defined
    at PacketHandler.handleMessage (/root/PacketHandler.js:197:37)
    at WebSocket.emit (events.js:85:17)
    at Receiver.onbinary (/root/node_modules/ws/lib/WebSocket.js:823:10)
    at /root/node_modules/ws/lib/Receiver.js:537:18
    at Receiver.applyExtensions (/root/node_modules/ws/lib/Receiver.js:364:5)
    at /root/node_modules/ws/lib/Receiver.js:531:14
    at Receiver.flush (/root/node_modules/ws/lib/Receiver.js:340:3)
    at Receiver.opcodes.2.finish (/root/node_modules/ws/lib/Receiver.js:542:12)
    at Receiver.expectHandler (/root/node_modules/ws/lib/Receiver.js:516:33)
    at Receiver.add (/root/node_modules/ws/lib/Receiver.js:95:24)

**Comment by JaraLowell** [comment]
That is also an older version of OgarServ, that issue is resolved in current git version. Though i not sure if it fixed in the release. This week i be testing the game mode versions if they all work we will make a new release.

**Comment by J0113** [comment]
@JaraLowell I've that bug as well, nice the it get's fixed!

**Comment by morenja** [comment]
close
